project:
  type: website
  output-dir: docs

website:
  title: "LOD Control in ThreeJS"
  navbar:
    left:
      - href: reports/index.qmd
        text: Home
      - reports/3d-model-LOD.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: public/styles.css
    toc: true



